### PR TITLE
Using stringstream triggers a frequent OOM on an esp8266.

### PR DESCRIPTION
**Pull request by FreeBear-nc**
A string implementation reduces the amount of memory allocations.

Addresses part of the issue: https://github.com/olegtarasov/esphome-opentherm/issues/15

### CODE REVIEW

**Comment by olegtarasov** [comment]
@FreeBear-nc I decided to go a bit further and moved some logging statements around trying to minimize the number of strings that are allocated and passed around. I've merged the result to `develop`. Can you test it out please? I don't have physical access to my boiler until weekend, unfortunately.

**Comment by FreeBear-nc** [comment]
GCC suggests the following:
```
@@ -546,7 +546,7 @@ std::string OpenTherm::format_bin(const uint8_t *data, size_t length) {
   result.resize(length * 8);
   for (int byte_idx = 0; byte_idx < length; ++byte_idx) {
     for (int bit_idx = 0; bit_idx < 8; ++bit_idx) {
-      result[byte_idx * 8 + bit_idx] = (char) ((data[byte_idx] >> bit_idx) & 1 + '0');
+      result[byte_idx * 8 + bit_idx] = (char) (((data[byte_idx] >> bit_idx) & 1) + '0');
     }
   }
```
But unless you intend to add a space between each group of bytes, there is no need for nested loops. To my mind, the whole function is messy with unnecessary typecasts. That said, my version could do with extra work to remove the call to string::push_back()... Will give it some more thought tomorrow.

**Comment by olegtarasov** [comment]
In my version I tried to adhere to the idea behind `format_hex`: https://github.com/esphome/esphome/blob/6e41c22e9d7f777a5c556725b1a54cf33a669e39/esphome/core/helpers.cpp#L352

We have a base function that takes an array of bytes which is then formatted to string, and we also have a template function that `reinterpret_cast`s any unsigned int to an array of bytes. I would argue this approach has several advantages:

1. When we call the template version, we don't need to specify data size, it's figured out automatically.
2. We don't upcast `uint8_t` to `uint32_t`, saving a microscopic amount of memory :)
3. We adhere to an established way of doing things, which is always a plus in large codebases.

I agree that you could do my version with a single loop, but nested loops look more readable IMO and it's not likely they add any overhead (you would still need to determine two indices with the single loop: the byte index and the bit index).

**Comment by FreeBear-nc** [comment]
> I agree that you could do my version with a single loop, but nested loops look more readable IMO and it's not likely they add any overhead (you would still need to determine two indices with the single loop: the byte index and the bit index).

I'll have a little think and see if I can come up with a compromise. Yes, using a C++ template solves the issue of upcasting uint8_t to uint32_t without incurring a run time penalty.

**Comment by FreeBear-nc** [comment]
Reworked a few lines and reduced the format_bin() function to a single for loop and simplified the template.
To my mind, improves readability and runs marginally faster (always a good thing with embedded code).

**Comment by olegtarasov** [comment]
I'm not sure this version is better: we are back to upcasting to `uint32_t`, and `format_bin` loses its versatility. Its current version in `develop` can handle arbitrary arrays of bytes, not only `uint32_t`. I'm actually thinking about moving new `format_bin` helpers to `esphome/core/helpers.h`, so it would be better to follow the pattern set by `format_hex` that already exists there.

**Comment by olegtarasov** [comment]
To suggest an actionable resolution:

1. We move `format_bin` helpers to `esphome/core/helpers.h` as it is in `develop` so that other integrations could use binary formatting as well as hex formatting. We could leave just the outer loop and unroll the inner loop into 8 separate lines, but I strongly suspect that compiler already does it, since it's a loop with fixed number of iterations.
2. We include all other changes to logging code that minimize the number of allocations and benefit the end users.

What do you say?

**Comment by FreeBear-nc** [comment]
Getting format_bin() in to helpers.h would be good. Gives the code more exposure, but before that happens, I'd suggest a couple of changes:
```
diff --git a/components/opentherm/opentherm.cpp b/components/opentherm/opentherm.cpp
index b0821fd..6f322c4 100644
--- a/components/opentherm/opentherm.cpp
+++ b/components/opentherm/opentherm.cpp
@@ -544,9 +544,9 @@ const char *OpenTherm::message_id_to_str(MessageId id) {
 std::string OpenTherm::format_bin(const uint8_t *data, size_t length) {
   std::string result;
   result.resize(length * 8);
-  for (int byte_idx = 0; byte_idx < length; ++byte_idx) {
+  for (int byte_idx = 0; byte_idx < length; byte_idx++) {
     for (int bit_idx = 0; bit_idx < 8; ++bit_idx) {
-      result[byte_idx * 8 + bit_idx] = (char) ((data[byte_idx] >> bit_idx) & 1 + '0');
+      result[byte_idx * 8 + bit_idx] = ((data[byte_idx] >> (7 - bit_idx)) & 1) + '0';
     }
   }
 ```
We both got the bit ordering wrong. LSB is always furthest to the left.
No need to cast to char when saving the result[x] - The compiler will see that it is a char automatically.

**Comment by olegtarasov** [comment]
I integrated the final logging changes into `develop`, along with some new code for boiler configuration sequence and an ability to change messages on the fly before they are sent to/from the boiler. Since I will be proposing `format_bin` to be included in core, I had to temporarily add `format_bin` to `opentherm.h/cpp` in this repo, so that code compiles. 

I'm aiming to keep `main` in sync with current state of OpenTherm in esphome, so I think this PR can be closed. I will use `develop` to accumulate all the changes so far, and open a single PR to esphome core.

**Comment by FreeBear-nc** [comment]
OOM issue resolved with commit bb5ebe8

**Pull request closed without merging**
